# Generated by Django 4.2.5 on 2023-10-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_cart_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_db',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
