# Generated by Django 4.2.5 on 2023-10-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_cart_db_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_db',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='cartImg'),
        ),
    ]
