# Generated by Django 4.2.5 on 2023-10-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_cart_db_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_db',
            name='Image',
        ),
    ]
